#!/bin/sh

# http://cis.stvincent.edu/html/tutorials/unix/bshellref
# http://www.grymoire.com/Unix/Sh.html


if [ $# -ne 3 ]; then
	echo "noisycopy METHOD SOURCE DESTINATION"
	echo "methods: todo!"
	exit 1
fi

METHOD=$1
SOURCE=$(readlink -f "$2")
DESTINATION=$(readlink -f "$3")

#echo "method = $METHOD"
#echo "source = $SOURCE"
#echo "destination = $DESTINATION"

if [ ! -r "$SOURCE" ]; then
	echo "Can't read from the source"
	exit 2
fi

if [ ! -w "$DESTINATION" ]; then
	echo "Can't write to the destination"
	exit 3
fi


# hold where the destination currently is, in step with the working directory
DESTINATION_CWD=$DESTINATION

breadth_discover() {
	if [ -f "$1" ]; then
		# source is a single file
		FILE_PATH=$(readlink -f "$i")
		echo "TODO: copy $FILE_PATH as per $METHOD into $DESTINATION_CWD"
		return
	fi
	
	# walk into this directory
	cd "$1"
	
	for i in *; do
		if [ -d "$i" ]; then
			local DESTINATION_LAST=$DESTINATION_CWD
			local DIR_NAME=${i##*/}
			DESTINATION_CWD="$DESTINATION_CWD/$DIR_NAME"
			echo "TODO: ensure $DIR_NAME destination folder exists ($DESTINATION_CWD)"

			breadth_discover "$i"

			DESTINATION_CWD=$DESTINATION_LAST
			cd ..
			
		elif [ -f "$i" ]; then
			local FILE_PATH=$(readlink -f "$i")
			echo "TODO: copy $FILE_PATH as per $METHOD into $DESTINATION_CWD"
		fi
		# ignore non-directory and non-file entries
	done
}

breadth_discover $SOURCE
